version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-backend-dev
    container_name: myapp-backend-dev
    restart: unless-stopped
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - database
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-frontend-dev
    container_name: myapp-frontend-dev
    restart: unless-stopped
    env_file:
      - ./frontend/.env.frontend.development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: npm run dev

  database:
    image: mongo:6.0
    container_name: myapp-database-dev
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
